
services:
  springboot-app:
    image: miapp:springboot  
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"            
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge