
services:
  springboot-app:
    image: miapp:springboot  
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"            
    environment:
      - SPRING_PROFILES_ACTIVE=dev  
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge