# Configuración común (puede contener solo algunos valores que no cambian)
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

---
# Perfil de desarrollo
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  # Opcional: Configuración específica para dev, si es necesario

---
# Perfil de producción
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-aws-mysql-endpoint:3306/your-database-name
    username: your-mysql-username
    password: your-mysql-password
  # Opcional: Configuración específica para prod