# Common configuration
spring:
  datasource:
    url: jdbc:mysql://your-aws-mysql-endpoint:3306/your-database-name
    username: your-mysql-username
    password: your-mysql-password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

# Local (dev) environment  
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver

# Production environment
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver