# Configuración común (aplicable a todos los perfiles)
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

---
# Perfil de desarrollo
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  # Opcional: otras configuraciones específicas de dev

---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-aws-mysql-endpoint:3306/your-database-name
    username: your-mysql-username
    password: your-mysql-password
