# Configuración común (aplicable a todos los perfiles)
server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc.time_zone: UTC
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
        # Para evitar "engine=InnoDB" y otras restricciones específicas de MySQL
        # en la creación en modo H2, no pongas esas líneas
        # Si quieres evitar también estrategias de nomenclatura antiguas, comenta o elimina esas líneas:
        # implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaCompliantImpl
        # physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        generate_statistics: false
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springdoc: DEBUG

---
# Perfil de desarrollo
spring:
  h2:
      console:
        enabled: true
        path: /h2-console
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password: 

  # Otras configuraciones específicas de dev

---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-aws-mysql-endpoint:3306/your-database-name
    username: 
    password: your-mysql-password