version: '3.8'

services:
  springboot-app:
    image: miapp:springboot  # Cambia por tu etiqueta o especifica build
    build:
      context: .
      dockerfile: Dockerfile  # Si tienes un Dockerfile en esta carpeta
    ports:
      - "8080:8080"            # Mapea el puerto del host al contenedor
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Configura perfiles o variables de entorno
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge